# Generated by Django 4.1.4 on 2023-01-10 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_news_options_news_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='img',
            field=models.ImageField(null=True, upload_to='article_img', verbose_name='Image'),
        ),
    ]
